#!/bin/bash
# Pyramid OpenShift post-deploy pre-start configuration

export PYTHON=python-3.3
export PATH=$PATH:~/$PYTHON/virtenv/bin/
export PYTHON_EGG_CACHE=~/$PYTHON/virtenv/lib/python3.3/site-packages

APP=pyramidapp

#echo "Moving egg.info files build"
#mv -f $OPENSHIFT_REPO_DIR/$APP/pyramidapp.egg-info $OPENSHIFT_REPO_DIR

source ~/$PYTHON/virtenv/bin/activate

# Have apache serve up all of our static resources
echo "Symlinking static resources from $APP/public"
ln -s $OPENSHIFT_REPO_DIR/$APP/$APP/static/* $OPENSHIFT_REPO_DIR/static/


cd $OPENSHIFT_REPO_DIR/$APP

# We're not doing 'install' to save space.
python setup.py test

